language: node_js
node_js:
- '8'

before_install:
  - stty cols 80

env:
sudo: required
addons:
  firefox: latest
  chrome: stable

before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3
script:
- testcafe chrome surveyjsio --reporter minimal
- testcafe firefox surveyjsio --reporter minimal
